### ISSUE TITLE
parallelise the generation of test reports 

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#107]
Currently the Maestro Client generates reports sequentially.  When you are running tests at scale (with say 100s of workers), the length of time to generate all the reports sequentially, quickly grows and adds significantly to the overall test-cycle.

The generation of the reports could be parallelised by submitting the individual tests to a suitably sized ThreadPoolExecutor.

**Comment by orpiske** [comment]
Good idea. I think that falls in line with reducing the post-processing time for the tests. I am adding this to 1.4 roadmap.

**Comment by orpiske** [comment]
I completely redesigned the report code and took a different approach. Report generation and aggregation is now done by a separate component that downloads, aggregates and indexes the report files automatically. It also makes the front-end/test code simpler, so no download logic is required. 

The preliminary/devel code is now on devel branch for larger testing.

**Comment by orpiske** [comment]
Completed reworked this feature on 1.5.
