### ISSUE TITLE
System information should be present on the report

### ISSUE THREAD

**Issue by orpiske** [maestro-performance/maestro-java#111]
Currently, the system information is available on the reports generated by Maestro ResultsDB tool. In previous versions (from the C code base), the system information was part of the reports (albeit in a hacky/cumbersome way). 

The test reports should display system information along with the reports without requiring the Results DB.

**Comment by Frawless** [comment]
The system properties collection is part of the [PR#116](https://github.com/maestro-performance/maestro-java/pull/116) . Currently waiting for review. There are some parts, which can be done better way so I expect some small changes.

**Comment by orpiske** [comment]
Thanks for the patch @Frawless. Here's some comments:
1. I think we need to leave the inspector code in place. The code as initialize proposed, reads the system information from the wokers' environment, but the SUT environment might be completely different. 
2. One idea is to pass some of the system information via CLI to the reporter. Those variables then could be read by the reporter code.

**Comment by orpiske** [comment]
Completed on 1.5.
