### ISSUE TITLE
FileNotFoundException during create test report

### ISSUE THREAD

**Issue by Frawless** [maestro-performance/maestro-java#35]
During create a report from test getting this error and the report is not finished correctly (missing some html design things, plots are ok):

> /opt/maestro/maestro-cli/bin/maestro-cli report -l info -d FixedRateTest/
> Running report
> org.maestro.cli.main.actions.ReportAction$HdrPlotterWrapperFactory.<init>:26 [INFO] Creating a custom HDR Plotter Factory
> org.maestro.reports.ReportGenerator.generate:129 [INFO] Building the file list to be processed by the report generator
> org.maestro.reports.ReportGenerator.generate:132 [INFO] There are 3 files to be processed
> org.maestro.reports.plotter.RatePlotterWrapper.plot:67 [INFO] Number of rate records to plot: 31
> org.maestro.reports.plotter.RatePlotterWrapper.plot:68 [INFO] Number of rate records in error: 0
> org.maestro.reports.plotter.RatePlotterWrapper.plot:67 [INFO] Number of rate records to plot: 31
> org.maestro.reports.plotter.RatePlotterWrapper.plot:68 [INFO] Number of rate records in error: 0
> org.maestro.reports.ReportGenerator.plotLatencyReportFile:88 [INFO] Plotting latency from ReportFile{sourceFile=FixedRateTest/receiver/success/0/10.37.145.123/receiverd-latency.hdr, normalizedFile=receiver/success/0/10.37.145.123/receiverd-latency.hdr, reportSuccessful=true, reportFailure=null, nodeType=RECEIVER, nodeHost='10.37.145', testNum=0, testSuccessful=true}
> org.maestro.reports.ReportGenerator.renderNodePage:113 [INFO] Processing report dir: FixedRateTest/receiver/success/0/10.37.145.123
> org.maestro.reports.ReportGenerator.renderNodePage:113 [INFO] Processing report dir: FixedRateTest/sender/success/0/10.37.145.88
> java.io.FileNotFoundException: Source 'file:/opt/maestro/maestro-cli-1.3.0-SNAPSHOT/lib/maestro-reports-1.3.0-SNAPSHOT.jar!/org/maestro/reports/modern/resources' does not exist
>         at org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405)
>         at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368)
>         at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268)
>         at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237)
>         at org.maestro.reports.index.IndexRenderer.copyResources(IndexRenderer.java:50)
>         at org.maestro.reports.ReportGenerator.renderReportIndex(ReportGenerator.java:106)
>         at org.maestro.reports.ReportGenerator.generate(ReportGenerator.java:158)
>         at org.maestro.cli.main.actions.ReportAction.run(ReportAction.java:94)
>         at org.maestro.cli.main.Main.main(Main.java:92)
> Report generated successfully

**Comment by orpiske** [comment]
I've just reviewed the test pipeline and the fix seems to be working. Therefore, I am closing the ticket. Thanks @Frawless for providing the fix.
