### ISSUE TITLE
Maestro Agent: Report Download

### ISSUE THREAD

**Issue by Frawless** [maestro-performance/maestro-java#68]
After the test execution, the report down-loader tries to download data from the Agent data server, however, there are no data for download, even no data is specified for donwload I think. The solution can be "skip" the agent peer during the report download.

> [INFO] Test successful on agent@.... after 0 executions
> [INFO] Test parameters used: FixedRateTestProfile{rate=0, parallelCount=5, maximumLatency=20000, duration=1m, messageSize='256'} AbstractTestProfile{testExecutionNumber=0}
> [ERROR] Error: null
> java.lang.NullPointerException
>         at org.maestro.reports.ReportsDownloader.downloadLastSuccessful(ReportsDownloader.java:119)
>         at org.maestro.tests.AbstractTestProcessor.processNotifySuccess(AbstractTestProcessor.java:118)
>         at org.maestro.client.exchange.MaestroNoteProcessor.processNotification(MaestroNoteProcessor.java:73)
>         at org.maestro.client.exchange.MaestroNoteProcessor.process(MaestroNoteProcessor.java:93)
> 
>         at org.maestro.tests.AbstractTestExecutor.processNotifications(AbstractTestExecutor.java:119)
>         at org.maestro.tests.rate.FixedRateTestExecutor.run(FixedRateTestExecutor.java:72)
>         at org.maestro.tests.TestExecutor$run.call(Unknown Source)
>         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
>         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
>         at singlepoint.FixedRate.run(FixedRate.groovy:128)
>         at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
>         at groovy.lang.GroovyShell.run(GroovyShell.java:229)
>         at groovy.lang.GroovyShell.run(GroovyShell.java:159)
>         at groovy.ui.GroovyMain.processOnce(GroovyMain.java:550)
>         at groovy.ui.GroovyMain.run(GroovyMain.java:337)
>         at groovy.ui.GroovyMain.process(GroovyMain.java:323)
>         at groovy.ui.GroovyMain.processArgs(GroovyMain.java:120)
>         at groovy.ui.GroovyMain.main(GroovyMain.java:100)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

>         at singlepoint.FixedRate.run(FixedRate.groovy:128)
>         at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:266)
>         at groovy.lang.GroovyShell.run(GroovyShell.java:229)
>         at groovy.lang.GroovyShell.run(GroovyShell.java:159)
>         at groovy.ui.GroovyMain.processOnce(GroovyMain.java:550)
>         at groovy.ui.GroovyMain.run(GroovyMain.java:337)
>         at groovy.ui.GroovyMain.process(GroovyMain.java:323)
>         at groovy.ui.GroovyMain.processArgs(GroovyMain.java:120)
>         at groovy.ui.GroovyMain.main(GroovyMain.java:100)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:108)
>         at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:130)

**Comment by orpiske** [comment]
@Frawless have you seen this, recently, on your tests? I believe may have been fixed w/ 7895b8071a94dfc49e83080b1fa232aeb3ed80de but a similar filtering may need to be implemented on your test case. Could you, please, check and let me know?

**Comment by orpiske** [comment]
After discussing w/ @Frawless we were able to verify that the issue was resolved. Therefore closing.
