### ISSUE TITLE
limitDestinations should distribute addresses across workers

### ISSUE THREAD

**Issue by lulf** [maestro-performance/maestro-java#82]
At present, the limitDestinations setting will only have an effect within a single worker. I.e. if parallelCount=1 and you have 50 senders and 50 receivers, setting limitDestinations=50, all workers will use the base address. 

Instead, if at startup, senders and receivers could be assigned an id from 0 to N (number of ids) and the total number of senders/receivers, they can choose a 'base index' from which to start the limitDestination enumeration.

A couple of messages like setBaseIndex() and setNumPeers()  could be used to assign the ids ahead of test start time.

**Comment by orpiske** [comment]
I like this idea and I think it wouldn't be very difficult to implement. It will need a couple of extra parameters/commands on the orchestration API, so I am marking it for 1.4. However, I will try to do it earlier, depending on my workload.

**Comment by orpiske** [comment]
Completed on 1.5 as part of the distribution strategy feature.
