### ISSUE TITLE
Test summary should include TLS and message durability information

### ISSUE THREAD

**Issue by k-wall** [maestro-performance/maestro-java#94]
The summary table in the report should include whether the test worker is using TLS or not, and the message durability setting (persistent or otherwise).

**Comment by orpiske** [comment]
Agreed. I like the idea. Earlier I had added the one for durability (on  93f838863db651615ed9148b15a847cbecc42105) along with others, but the TLS is still missing. I will add that one and include it in the next build.

**Comment by orpiske** [comment]
Done: https://github.com/maestro-performance/maestro-java/commit/0daaaf2ce1de113201b52cd23223779ebb861b7e (followed by a subsequent commit that tries to cleanup the way the messages are present). 

I'll be building a new release soon, so this should be part of 1.3.4.
